version: "3"

services:
  mysql-dev:
    image: mysql:8.0.31
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: best-emoji
    ports:
      - "3308:3306"
