import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

export const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const meme = trpc.example.meme.useQuery({ text: "fuck" });

  return (
    <>
      <Head>
        <title>Best Emoji</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1>{hello.data?.greeting}</h1>
        <div>&#128512;</div>
      </main>
    </>
  );
};

export default Home;
